name: Deploy no EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
   steps:
      - name: Clona o código
        uses: actions/checkout@v2

      - name: Conecta no EC2 e limpa o ambiente
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop contador || true
            docker rm contador || true
            docker rmi contador:latest || true
            rm -rf contador-cliques || true
            mkdir contador-cliques

      - name: Copia arquivos para EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "./"
          target: "contador-cliques"

      - name: Build e run do container com verificação
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd contador-cliques
            docker build -t contador .
            if [ $? -ne 0 ]; then
              echo "❌ Erro no docker build"
              exit 1
            fi

            docker run -d -p 5000:5000 --name contador contador
            if [ $? -ne 0 ]; then
              echo "❌ Erro ao subir o container"
              exit 1
            fi

            docker ps | grep contador
            if [ $? -ne 0 ]; then
              echo "❌ Container 'contador' não está rodando após o run"
              exit 1
            fi

            echo "✅ Deploy concluído com sucesso!"
